name: Build and publish docker image for production

on:
  push:
    branches: [ master ]

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    name: Build and publish
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Get short SHA
      id: slug
      run: echo "::set-output name=sha7::$(echo ${GITHUB_SHA} | cut -c1-7)"

    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
  
    - name: Get repository variable in lowercase
      run: echo "REPOSITORY=$(echo $GITHUB_REPOSITORY | tr '[A-Z]' '[a-z]')" >> $GITHUB_ENV

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
  
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}

    - name: Dotnet publish linux-arm64
      run: dotnet publish ConsoleApp1.csproj -c Release -o deploy -r linux-arm64 

    - name: Push linux-arm64 to GitHub Container Registry
      uses: docker/build-push-action@v2
      with:
        context: .
        platforms: linux/arm64
        build-args: BUILD_FROM=3.1-focal-arm64v8
        push: true
        tags: ghcr.io/${{ env.REPOSITORY }}:master